// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiEntityFrameworkCoreDemo.Data;

#nullable disable

namespace WebApiEntityFrameworkCoreDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121214603_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BooksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = new Guid("fdf77ea8-6758-482d-93f4-83e0da2517fb"),
                            BooksId = new Guid("2c5d2764-8c5f-4755-b11f-10e457ded0cf")
                        },
                        new
                        {
                            AuthorsId = new Guid("fdf77ea8-6758-482d-93f4-83e0da2517fb"),
                            BooksId = new Guid("f54d8cd9-eb63-44d9-8fa7-64e397b8c77b")
                        },
                        new
                        {
                            AuthorsId = new Guid("faf8ed2a-e995-4933-ad0b-4f34366b9a1f"),
                            BooksId = new Guid("78606e63-e180-4d09-b668-3744a26457c0")
                        },
                        new
                        {
                            AuthorsId = new Guid("faf8ed2a-e995-4933-ad0b-4f34366b9a1f"),
                            BooksId = new Guid("2c5d2764-8c5f-4755-b11f-10e457ded0cf")
                        });
                });

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdf77ea8-6758-482d-93f4-83e0da2517fb"),
                            BirthDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vasya P"
                        },
                        new
                        {
                            Id = new Guid("faf8ed2a-e995-4933-ad0b-4f34366b9a1f"),
                            BirthDate = new DateTime(1910, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petya R"
                        });
                });

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c5d2764-8c5f-4755-b11f-10e457ded0cf"),
                            Description = "Description1",
                            Price = 123.11m,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = new Guid("f54d8cd9-eb63-44d9-8fa7-64e397b8c77b"),
                            Description = "Description2",
                            Price = 113.11m,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = new Guid("78606e63-e180-4d09-b668-3744a26457c0"),
                            Description = "Description3",
                            Price = 1523.11m,
                            Title = "Title3"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("WebApiEntityFrameworkCoreDemo.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiEntityFrameworkCoreDemo.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
