// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiEntityFrameworkCoreDemo.Data;

#nullable disable

namespace WebApiEntityFrameworkCoreDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121212455_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c374e5f1-cc7c-4248-aad8-8f87bd5aa3e6"),
                            BirthDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vasya P"
                        },
                        new
                        {
                            Id = new Guid("693bf6f7-71f2-4706-a6cb-5511c978f511"),
                            BirthDate = new DateTime(1910, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petya R"
                        });
                });

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("639a71e2-d519-46c8-896d-d81ccbfefc14"),
                            AuthorId = new Guid("c374e5f1-cc7c-4248-aad8-8f87bd5aa3e6"),
                            Description = "Description1",
                            Price = 123.11m,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = new Guid("10e9643b-4691-4cb3-b00c-09895ee81acc"),
                            AuthorId = new Guid("c374e5f1-cc7c-4248-aad8-8f87bd5aa3e6"),
                            Description = "Description2",
                            Price = 113.11m,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = new Guid("cce169b1-065f-40e2-8a74-403042d52ef0"),
                            AuthorId = new Guid("693bf6f7-71f2-4706-a6cb-5511c978f511"),
                            Description = "Description3",
                            Price = 1523.11m,
                            Title = "Title3"
                        });
                });

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Book", b =>
                {
                    b.HasOne("WebApiEntityFrameworkCoreDemo.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WebApiEntityFrameworkCoreDemo.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
